# Generated by Django 4.2.7 on 2025-04-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_actualizado', 'Pedido Actualizado'), ('pago_recibido', 'Pago Recibido'), ('solicitud_nueva', 'Nueva Solicitud'), ('alerta_inventario', 'Alerta de Inventario'), ('recordatorio', 'Recordatorio'), ('sistema', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('pedido_personalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedidopersonalizado')),
                ('solicitud_confeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.solicitudconfeccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_pedidos', models.BooleanField(default=True)),
                ('notificar_pagos', models.BooleanField(default=True)),
                ('notificar_solicitudes', models.BooleanField(default=True)),
                ('notificar_inventario', models.BooleanField(default=True)),
                ('notificar_recordatorios', models.BooleanField(default=True)),
                ('notificar_sistema', models.BooleanField(default=True)),
                ('email_pedidos', models.BooleanField(default=True)),
                ('email_pagos', models.BooleanField(default=True)),
                ('email_solicitudes', models.BooleanField(default=True)),
                ('email_inventario', models.BooleanField(default=False)),
                ('email_recordatorios', models.BooleanField(default=False)),
                ('email_sistema', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
    ]
