# Generated by Django 4.2.7 on 2025-04-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20)),
                ('tipo_transaccion', models.CharField(choices=[('pedido_estandar', 'Pedido Estándar'), ('pedido_personalizado', 'Pedido Personalizado'), ('solicitud_confeccion', 'Solicitud de Confección')], max_length=30)),
                ('id_transaccion_externa', models.CharField(max_length=100, null=True, unique=True)),
                ('metodo_pago', models.CharField(max_length=50, null=True)),
                ('detalles_pago', models.JSONField(default=dict)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('pedido_personalizado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedidopersonalizado')),
                ('solicitud_confeccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.solicitudconfeccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
