# Generated by Django 4.2.7 on 2025-04-16 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0016_servicio'),
        ('pedidos', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='descripcion_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='material_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidopersonalizado',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudconfeccion',
            name='empresa_integral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.microempresaintegral'),
        ),
    ]
