# Generated by Django 5.0.1 on 2025-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_detallepedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='comentarios_cotizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='fecha_cotizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='precio_por_prenda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='tiempo_estimado',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en días', null=True),
        ),
    ]
