# Generated by Django 4.2.7 on 2025-04-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('ventas', 'Reporte de Ventas'), ('produccion', 'Reporte de Producción'), ('inventario', 'Reporte de Inventario'), ('financiero', 'Reporte Financiero')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('empresa_integral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.microempresaintegral')),
                ('empresa_satelite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.microempresasatelite')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('fecha', models.DateField()),
                ('ventas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedidos_completados', models.PositiveIntegerField(default=0)),
                ('pedidos_pendientes', models.PositiveIntegerField(default=0)),
                ('produccion_total', models.PositiveIntegerField(default=0)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empresa_integral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.microempresaintegral')),
                ('empresa_satelite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.microempresasatelite')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['-fecha'],
                'unique_together': {('empresa_integral', 'empresa_satelite', 'periodo', 'fecha')},
            },
        ),
    ]
