# Generated by Django 4.2.7 on 2025-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_microempresaintegral_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='microempresasatelite',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
    ]
