# Generated by Django 4.2.7 on 2025-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_microempresaintegral_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microempresasatelite',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos_satelite/'),
        ),
    ]
