# Generated by Django 4.2.7 on 2025-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_microempresasatelite_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microempresasatelite',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logos_satelite/'),
        ),
    ]
