# Generated by Django 4.2.7 on 2025-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_microempresasatelite_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microempresaintegral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logos_integral/'),
        ),
    ]
