# Generated by Django 4.2.7 on 2025-04-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_comentarioproducto_calificacionproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microempresasatelite',
            name='capacidad_produccion',
        ),
    ]
