# Generated by Django 4.2.7 on 2025-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_categoriaproducto_productoterminado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
