# Generated by Django 4.2.7 on 2025-04-15 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_categoriaproducto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.categoriaproducto'),
        ),
    ]
