# Generated by Django 4.2.7 on 2025-04-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_alter_productoterminado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.categoriaproducto'),
        ),
    ]
