# Generated by Django 4.2.7 on 2025-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_alter_materiaprima_options_materiaprima_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientomateriaprima',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
