# Generated by Django 5.0.1 on 2025-05-18 22:01

import django.db.models.deletion
import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_alter_materiaprima_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=empresas.models.Maquina.get_upload_path),
        ),
        migrations.AddField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(default='Nueva Máquina', max_length=100),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='empresas.microempresasatelite'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'En Mantenimiento'), ('inactiva', 'Inactiva')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='marca',
            field=models.CharField(default='Sin Especificar', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='modelo',
            field=models.CharField(default='Sin Especificar', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(default='Industrial', max_length=50),
        ),
    ]
