# Generated by Django 5.0.1 on 2025-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_maquina_cantidad_maquina_descripcion_maquina_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microempresasatelite',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='tipo',
            field=models.CharField(default='satelite', max_length=20),
        ),
    ]
