# Generated by Django 5.0.1 on 2025-05-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_microempresasatelite_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionProducto',
        ),
    ]
